### PR TITLE
chore: hide sensitive vars

### PR DESCRIPTION
**Pull request by datnguye**

### CODE REVIEW

**Comment by b-per** [comment]
Thanks for raising this.

Wouldn't it be actually better to update the variable below as sensitive, so that all the downstream fields referencing it will also be considered sensitive?

https://github.com/b-per/dbt-terraform-modules/blob/e5c6ee7c385990b9010e784047c1100afa1d8642/modules/github/variables.tf#L1-L5

**Comment by datnguye** [comment]
> Thanks for raising this.
> 
> Wouldn't it be actually better to update the variable below as sensitive, so that all the downstream fields referencing it will also be considered sensitive?
> 
> https://github.com/b-per/dbt-terraform-modules/blob/e5c6ee7c385990b9010e784047c1100afa1d8642/modules/github/variables.tf#L1-L5

Yeah that's perfectly working with `sensitive = true` and better 👍 

This was just raising while I used the `null provider` with customized command, and the local variable value got exposed to the pipeline log.

PS: I love these modules ;-) Thanks for making them

**Comment by datnguye** [comment]
So as the result, do you want me to make the change to sensitive vars? If not, I'm happy to close the PR now.

Thanks

**Comment by b-per** [comment]
If you are OK creating a PR to make the field sensitive I can approve and merge it!

> PS: I love these modules ;-) Thanks for making them

Thanks for this and glad this has been useful. The modules haven't had a lot of love lately but we might have something cooking to add more of them and make them better.

**Comment by datnguye** [comment]
> If you are OK creating a PR to make the field sensitive I can approve and merge it!
> 
> > PS: I love these modules ;-) Thanks for making them
> 
> Thanks for this and glad this has been useful. The modules haven't had a lot of love lately but we might have something cooking to add more of them and make them better.

It's done. Thanks

**Review by b-per — APPROVED** [review]

**Pull request merged**
